!MENU_BANK_START = $DFEA00
!MENU_BANK_DB = $DF00

!MENU_CONTROLLER = $8B
!MENU_CONTROLLER_NEW = $8F
!MENU_CONTROLLER_PREV = $97
!MENU_INPUT = #$3000 ; select + start

!MENU_MODE = $7EFFE0
!MENU_SEL = $7EFFE2
!MENU_VAL = $7EFFE4
!MENU_MAX = $7EFFE6
!MENU_SKIP = $7EFFE8
!MENU_PTR = $7EFFEA
!MENU_INPUT_TIMER = $7EFFEC

!MENU_STACK = $7FFFE0 ; first 2 bytes are the "stack pointer", then growing upwards is menu pointers
