#!/usr/bin/env python
import io
import os
import sys

if len(sys.argv) != 3:
   print("bk2_input_log_to_demo.py <input_log_file> <demo_output_file>")
   sys.exit()
else:
   input_name = sys.argv[1]
   demo_name = sys.argv[2]

input_file = io.open(os.path.join(os.path.dirname(os.path.realpath(__file__)), input_name), "r")
input_lines = input_file.readlines()
input_file.close()

demo_file = io.open(os.path.join(os.path.dirname(os.path.realpath(__file__)), demo_name), "w", newline='\n')
demo_file.write("\n; ---------------")
demo_file.write("\n; Demo Export")
demo_file.write("\n; (autogenerated)")
demo_file.write("\n; ---------------\n\n")

current_input = 0
previous_line = None
previous_count = 0
for line in input_lines:
   if len(line) > 16 and '|' == line[0] and '|' == line[3] and '|' == line[16]:
      if previous_count > 0 and previous_line != line:
         demo_file.write(f'    dw ${previous_count:04X}, ${current_input:04X}, $0000    ; {previous_line[4:16]}\n')
         previous_line = None
         previous_count = 0
      if previous_line is None:
         previous_line = line
         current_input = 0
         if 'U' == line[4]:
            current_input += 0x800
         if 'D' == line[5]:
            current_input += 0x400
         if 'L' == line[6]:
            current_input += 0x200
         if 'R' == line[7]:
            current_input += 0x100
         if 's' == line[8]:
            current_input += 0x2000
         if 'S' == line[9]:
            current_input += 0x1000
         if 'Y' == line[10]:
            current_input += 0x4000
         if 'B' == line[11]:
            current_input += 0x8000
         if 'X' == line[12]:
            current_input += 0x0040
         if 'A' == line[13]:
            current_input += 0x0080
         if 'l' == line[14]:
            current_input += 0x0020
         if 'r' == line[15]:
            current_input += 0x0010
      previous_count = previous_count + 1
if previous_count > 0:
   demo_file.write(f'    dw ${previous_count:04X}, ${current_input:04X}, $0000    ; {previous_line[4:16]}\n\n')

demo_file.close()

