
; ---------------
; Room Names
; (autogenerated)
; ---------------

org $E78000
print pc, " roomnames start"
RoomNameTextTable:
ROOM:

org $E791F8
  .LandingSite
    db $28, "Landing Site", $FF
warnpc $E79212

org $E792B3
  .GauntletEntrance
    db $28, "Gauntlet Entrance", $FF
warnpc $E792CD

org $E792FD
  .ParlorAndAlcatraz
    db $28, "Parlor and Alcatraz", $FF
warnpc $E79317

org $E793AA
  .CrateriaPowerBombs
    db $28, "Crateria Power Bombs", $FF
warnpc $E793C4

org $E793D5
  .CrateriaSaveRoom
    db $28, "Crateria Save Room", $FF
warnpc $E793EF

org $E793FE
  .WestOcean
    db $28, "West Ocean", $FF
warnpc $E79418

org $E79461
  .BowlingAlleyPath
    db $28, "Bowling Alley Path", $FF
warnpc $E7947B

org $E7948C
  .CrateriaKihunterRoom
    db $28, "Crateria Kihunter Room", $FF
warnpc $E794A6

org $E794CC
  .ForgottenHighwayElev
    db $28, "Forgotten Highway Elev", $FF
warnpc $E794E6

org $E794FD
  .EastOcean
    db $28, "East Ocean", $FF
warnpc $E79517

org $E79552
  .ForgottenHighwayKagos
    db $28, "Forgotten Highway Kagos", $FF
warnpc $E7956C

org $E7957D
  .CrabMaze
    db $28, "Crab Maze", $FF
warnpc $E79597

org $E795A8
  .ForgottenHighwayElbow
    db $28, "Forgotten Highway Elbow", $FF
warnpc $E795C2

org $E795D4
  .CrateriaTube
    db $28, "Crateria Tube", $FF
warnpc $E795EE

org $E795FF
  .TheMoat
    db $28, "The Moat", $FF
warnpc $E79619

org $E7962A
  .RedBrinstarElevRoom
    db $28, "Red Brinstar Elev Room", $FF
warnpc $E79644

org $E7965B
  .GauntletETankRoom
    db $28, "Gauntlet E-Tank Room", $FF
warnpc $E79675

org $E7968F
  .PreBowling
    db $28, "Pre-Bowling", $FF
warnpc $E796A9

org $E796BA
  .Climb
    db $28, "Climb", $FF
warnpc $E796D4

org $E7975C
  .PitRoom
    db $28, "Pit Room", $FF
warnpc $E79776

org $E797B5
  .ElevToBlueBrinstar
    db $28, "Elev to Blue Brinstar", $FF
warnpc $E797CF

org $E79804
  .BombTorizoRoom
    db $28, "Bomb Torizo Room", $FF
warnpc $E7981E

org $E79879
  .Flyway
    db $28, "Flyway", $FF
warnpc $E79893

org $E798E2
  .PreMapFlyway
    db $28, "Pre-Map Flyway", $FF
warnpc $E798FC

org $E7990D
  .TerminatorRoom
    db $28, "Terminator Room", $FF
warnpc $E79927

org $E79938
  .GreenBrinElevRoom
    db $28, "Green Brin Elev Room", $FF
warnpc $E79952

org $E79969
  .LowerMushrooms
    db $28, "Lower Mushrooms", $FF
warnpc $E79983

org $E79994
  .CrateriaMapRoom
    db $28, "Crateria Map Room", $FF
warnpc $E799AE

org $E799BD
  .GreenPiratesShaft
    db $28, "Green Pirates Shaft", $FF
warnpc $E799D7

org $E799F9
  .CrateriaSuperRoom
    db $28, "Crateria Super Room", $FF
warnpc $E79A13

org $E79A44
  .FinalMissileBombway
    db $28, "Final Missile Bombway", $FF
warnpc $E79A5E

org $E79A90
  .TheFinalMissile
    db $28, "The Final Missile", $FF
warnpc $E79AAA

org $E79AD9
  .GreenBrinMainShaft
    db $28, "Green Brin Main Shaft", $FF
warnpc $E79AF3

org $E79B5B
  .SporeSpawnSuperRoom
    db $28, "Spore Spawn Super Room", $FF
warnpc $E79B75

org $E79B9D
  .BrinstarPreMapRoom
    db $28, "Brinstar Pre-Map Room", $FF
warnpc $E79BB7

org $E79BC8
  .EarlySupersRoom
    db $28, "Early Supers Room", $FF
warnpc $E79BE2

org $E79C07
  .BrinstarReserveTank
    db $28, "Brinstar Reserve Tank", $FF
warnpc $E79C21

org $E79C35
  .BrinstarMapRoom
    db $28, "Brinstar Map Room", $FF
warnpc $E79C4F

org $E79C5E
  .GreenBrinFirefleas
    db $28, "Green Brin Firefleas", $FF
warnpc $E79C78

org $E79C89
  .GreenBrinMissileRefi
    db $28, "Green Brin Missile Refi", $FF
warnpc $E79CA3

org $E79CB3
  .DachoraRoom
    db $28, "Dachora Room", $FF
warnpc $E79CCD

org $E79D19
  .BigPink
    db $28, "Big Pink", $FF
warnpc $E79D33

org $E79D9C
  .SporeSpawnKihunters
    db $28, "Spore Spawn Kihunters", $FF
warnpc $E79DB6

org $E79DC7
  .SporeSpawnRoom
    db $28, "Spore Spawn Room", $FF
warnpc $E79DE1

org $E79E11
  .PinkBrinPowerBombs
    db $28, "Pink Brin Power Bombs", $FF
warnpc $E79E2B

org $E79E52
  .GreenHillZone
    db $28, "Green Hill Zone", $FF
warnpc $E79E6C

org $E79E9F
  .MorphBallRoom
    db $28, "Morph Ball Room", $FF
warnpc $E79EB9

org $E79F11
  .ConstructionZone
    db $28, "Construction Zone", $FF
warnpc $E79F2B

org $E79F64
  .BlueBrinstarETank
    db $28, "Blue Brinstar E-Tank", $FF
warnpc $E79F7E

org $E79FBA
  .NoobBridge
    db $28, "Noob Bridge", $FF
warnpc $E79FD4

org $E79FE5
  .GreenBrinstarBeetoms
    db $28, "Green Brinstar Beetoms", $FF
warnpc $E79FFF

org $E7A011
  .EtecoonETankRoom
    db $28, "Etecoon E-Tank Room", $FF
warnpc $E7A02B

org $E7A051
  .EtecoonSuperRoom
    db $28, "Etecoon Super Room", $FF
warnpc $E7A06B

org $E7A07B
  .DachoraEnergyRefill
    db $28, "Dachora Energy Refill", $FF
warnpc $E7A095

org $E7A0A4
  .SporeSpawnFarming
    db $28, "Spore Spawn Farming", $FF
warnpc $E7A0BE

org $E7A0D2
  .WaterwayETankRoom
    db $28, "Waterway E-Tank Room", $FF
warnpc $E7A0EC

org $E7A107
  .FirstMissileRoom
    db $28, "First Missile Room", $FF
warnpc $E7A121

org $E7A130
  .PinkBrinstarHoppers
    db $28, "Pink Brinstar Hoppers", $FF
warnpc $E7A14A

org $E7A15B
  .HopperEnergyTankRoom
    db $28, "Hopper Energy Tank Room", $FF
warnpc $E7A175

org $E7A184
  .BigPinkSaveRoom
    db $28, "Big Pink Save Room", $FF
warnpc $E7A19E

org $E7A1AD
  .BlueBrinstarBoulders
    db $28, "Blue Brinstar Boulders", $FF
warnpc $E7A1C7

org $E7A1D8
  .BillyMaysRoom
    db $28, "Billy Mays Room", $FF
warnpc $E7A1F2

org $E7A201
  .GreenBrinSaveRoom
    db $28, "Green Brin Save Room", $FF
warnpc $E7A21B

org $E7A22A
  .EtecoonSaveRoom
    db $28, "Etecoon Save Room", $FF
warnpc $E7A244

org $E7A253
  .RedTower
    db $28, "Red Tower", $FF
warnpc $E7A26D

org $E7A293
  .RedBrinstarFirefleas
    db $28, "Red Brinstar Firefleas", $FF
warnpc $E7A2AD

org $E7A2CE
  .XRayScopeRoom
    db $28, "X-Ray Scope Room", $FF
warnpc $E7A2E8

org $E7A2F7
  .Hellway
    db $28, "Hellway", $FF
warnpc $E7A311

org $E7A322
  .CaterpillarRoom
    db $28, "Caterpillar Room", $FF
warnpc $E7A33C

org $E7A37C
  .BetaPowerBombRoom
    db $28, "Beta Power Bomb Room", $FF
warnpc $E7A396

org $E7A3AE
  .AlphaPowerBombRoom
    db $28, "Alpha Power Bomb Room", $FF
warnpc $E7A3C8

org $E7A3DD
  .SkreeBoostRoom
    db $28, "Skree Boost Room", $FF
warnpc $E7A3F7

org $E7A408
  .BelowSpazer
    db $28, "Below Spazer", $FF
warnpc $E7A422

org $E7A447
  .SpazerRoom
    db $28, "Spazer Room", $FF
warnpc $E7A461

org $E7A471
  .WarehouseZeelaRoom
    db $28, "Warehouse Zeela Room", $FF
warnpc $E7A48B

org $E7A4B1
  .WarehouseETankRoom
    db $28, "Warehouse E-Tank Room", $FF
warnpc $E7A4CB

org $E7A4DA
  .WarehouseKihunterRoom
    db $28, "Warehouse Kihunter Room", $FF
warnpc $E7A4F4

org $E7A521
  .BabyKraidRoom
    db $28, "Baby Kraid Room", $FF
warnpc $E7A53B

org $E7A56B
  .KraidEyeDoorRoom
    db $28, "Kraid Eye Door Room", $FF
warnpc $E7A585

org $E7A59F
  .KraidRoom
    db $28, "Kraid Room", $FF
warnpc $E7A5B9

org $E7A5ED
  .StatuesHallway
    db $28, "Statues Hallway", $FF
warnpc $E7A607

org $E7A618
  .SloatersRefill
    db $28, "Sloaters Refill", $FF
warnpc $E7A632

org $E7A641
  .KraidRefillStations
    db $28, "Kraid Refill Stations", $FF
warnpc $E7A65B

org $E7A66A
  .StatuesRoom
    db $28, "Statues Room", $FF
warnpc $E7A684

org $E7A6A1
  .WarehouseEntrance
    db $28, "Warehouse Entrance", $FF
warnpc $E7A6BB

org $E7A6E2
  .VariaSuitRoom
    db $28, "Varia Suit Room", $FF
warnpc $E7A6FC

org $E7A70B
  .WarehouseSaveRoom
    db $28, "Warehouse Save Room", $FF
warnpc $E7A725

org $E7A734
  .RedBrinstarSaveRoom
    db $28, "Red Brinstar Save Room", $FF
warnpc $E7A74E

org $E7A75D
  .IceBeamAcidRoom
    db $28, "Ice Beam Acid Room", $FF
warnpc $E7A777

org $E7A788
  .Cathedral
    db $28, "Cathedral", $FF
warnpc $E7A7A2

org $E7A7B3
  .CathedralEntrance
    db $28, "Cathedral Entrance", $FF
warnpc $E7A7CD

org $E7A7DE
  .BusinessCenter
    db $28, "Business Center", $FF
warnpc $E7A7F8

org $E7A815
  .IceBeamGateRoom
    db $28, "Ice Beam Gate Room", $FF
warnpc $E7A82F

org $E7A865
  .IceBeamTutorialRoom
    db $28, "Ice Beam Tutorial Room", $FF
warnpc $E7A87F

org $E7A890
  .IceBeamRoom
    db $28, "Ice Beam Room", $FF
warnpc $E7A8AA

org $E7A8B9
  .IceBeamSnakeRoom
    db $28, "Ice Beam Snake Room", $FF
warnpc $E7A8D3

org $E7A8F8
  .CrumbleShaft
    db $28, "Crumble Shaft", $FF
warnpc $E7A912

org $E7A923
  .CrocomireSpeedway
    db $28, "Crocomire Speedway", $FF
warnpc $E7A93D

org $E7A98D
  .CrocomireRoom
    db $28, "Crocomire's Room", $FF
warnpc $E7A9A7

org $E7A9E5
  .HiJumpBootsRoom
    db $28, "Hi Jump Boots Room", $FF
warnpc $E7A9FF

org $E7AA0E
  .CrocomireEscape
    db $28, "Crocomire Escape", $FF
warnpc $E7AA28

org $E7AA41
  .HiJumpETankRoom
    db $28, "Hi Jump E-Tank Room", $FF
warnpc $E7AA5B

org $E7AA82
  .PostCrocFarmingRoom
    db $28, "Post Croc Farming Room", $FF
warnpc $E7AA9C

org $E7AAB5
  .PostCrocSaveRoom
    db $28, "Post Croc Save Room", $FF
warnpc $E7AACF

org $E7AADE
  .PostCrocPowerBombs
    db $28, "Post Croc Power Bombs", $FF
warnpc $E7AAF8

org $E7AB07
  .PostCrocomireShaft
    db $28, "Post Crocomire Shaft", $FF
warnpc $E7AB21

org $E7AB3B
  .PostCrocMissileRoom
    db $28, "Post Croc Missile Room", $FF
warnpc $E7AB55

org $E7AB64
  .GrappleTutorialRoom3
    db $28, "Grapple Tutorial Room 3", $FF
warnpc $E7AB7E

org $E7AB8F
  .PostCrocJumpRoom
    db $28, "Post Croc Jump Room", $FF
warnpc $E7ABA9

org $E7ABD2
  .GrappleTutorialRoom2
    db $28, "Grapple Tutorial Room 2", $FF
warnpc $E7ABEC

org $E7AC00
  .GrappleTutorialRoom1
    db $28, "Grapple Tutorial Room 1", $FF
warnpc $E7AC1A

org $E7AC2B
  .GrappleBeamRoom
    db $28, "Grapple Beam Room", $FF
warnpc $E7AC45

org $E7AC5A
  .NorfairReserveTank
    db $28, "Norfair Reserve Tank", $FF
warnpc $E7AC74

org $E7AC83
  .GreenBubblesMissiles
    db $28, "Green Bubbles Missiles", $FF
warnpc $E7AC9D

org $E7ACB3
  .BubbleMountain
    db $28, "Bubble Mountain", $FF
warnpc $E7ACCD

org $E7ACF0
  .SpeedBoosterHall
    db $28, "Speed Booster Hall", $FF
warnpc $E7AD0A

org $E7AD1B
  .SpeedBoosterRoom
    db $28, "Speed Booster Room", $FF
warnpc $E7AD35

org $E7AD5E
  .SingleChamber
    db $28, "Single Chamber", $FF
warnpc $E7AD78

org $E7ADAD
  .DoubleChamber
    db $28, "Double Chamber", $FF
warnpc $E7ADC7

org $E7ADDE
  .WaveBeamRoom
    db $28, "Wave Beam Room", $FF
warnpc $E7ADF8

org $E7AE07
  .SpikyPlatformsTunnel
    db $28, "Spiky Platforms Tunnel", $FF
warnpc $E7AE21

org $E7AE32
  .VolcanoRoom
    db $28, "Volcano Room", $FF
warnpc $E7AE4C

org $E7AE74
  .KronicBoostRoom
    db $28, "Kronic Boost Room", $FF
warnpc $E7AE8E

org $E7AEB4
  .MagdolliteTunnel
    db $28, "Magdollite Tunnel", $FF
warnpc $E7AECE

org $E7AEDF
  .PurpleShaft
    db $28, "Purple Shaft", $FF
warnpc $E7AEF9

org $E7AF14
  .LavaDiveRoom
    db $28, "Lava Dive Room", $FF
warnpc $E7AF2E

org $E7AF3F
  .LowerNorfairElevator
    db $28, "Lower Norfair Elevator", $FF
warnpc $E7AF59

org $E7AF72
  .UpperNorfFarmingRoom
    db $28, "Upper Norf Farming Room", $FF
warnpc $E7AF8C

org $E7AFA3
  .RisingTide
    db $28, "Rising Tide", $FF
warnpc $E7AFBD

org $E7AFCE
  .AcidSnakesTunnel
    db $28, "Acid Snakes Tunnel", $FF
warnpc $E7AFE8

org $E7AFFB
  .SpikyAcidSnakesTunnel
    db $28, "Spiky Acid Snakes Tunnel", $FF
warnpc $E7B015

org $E7B026
  .NutellaRefill
    db $28, "Nutella Refill", $FF
warnpc $E7B040

org $E7B051
  .PurpleFarmingRoom
    db $28, "Purple Farming Room", $FF
warnpc $E7B06B

org $E7B07A
  .BatCave
    db $28, "Bat Cave", $FF
warnpc $E7B094

org $E7B0B4
  .NorfairMapRoom
    db $28, "Norfair Map Room", $FF
warnpc $E7B0CE

org $E7B0DD
  .BubbleMountainSave
    db $28, "Bubble Mountain Save", $FF
warnpc $E7B0F7

org $E7B106
  .FrogSpeedway
    db $28, "Frog Speedway", $FF
warnpc $E7B120

org $E7B139
  .RedPirateShaft
    db $28, "Red Pirate Shaft", $FF
warnpc $E7B153

org $E7B167
  .FrogSavestation
    db $28, "Frog Savestation", $FF
warnpc $E7B181

org $E7B192
  .CrocomireSaveRoom
    db $28, "Crocomire Save Room", $FF
warnpc $E7B1AC

org $E7B1BB
  .LNElevatorSaveRoom
    db $28, "LN Elevator Save Room", $FF
warnpc $E7B1D5

org $E7B1E5
  .AcidStatueRoom
    db $28, "Acid Statue Room", $FF
warnpc $E7B1FF

org $E7B236
  .MainHall
    db $28, "Main Hall", $FF
warnpc $E7B250

org $E7B283
  .GoldenTorizoRoom
    db $28, "Golden Torizo's Room", $FF
warnpc $E7B29D

org $E7B2DA
  .FastRipperRoom
    db $28, "Fast Ripper Room", $FF
warnpc $E7B2F4

org $E7B305
  .GTEnergyRecharge
    db $28, "GT Energy Recharge", $FF
warnpc $E7B31F

org $E7B32E
  .RidleyRoom
    db $28, "Ridley's Room", $FF
warnpc $E7B348

org $E7B37A
  .LNFarmingRoom
    db $28, "LN Farming Room", $FF
warnpc $E7B394

org $E7B3A5
  .FastPillarsSetupRoom
    db $28, "Fast Pillars Setup Room", $FF
warnpc $E7B3BF

org $E7B40A
  .MickeyMouseRoom
    db $28, "Mickey Mouse Room", $FF
warnpc $E7B424

org $E7B457
  .PillarRoom
    db $28, "Pillar Room", $FF
warnpc $E7B471

org $E7B482
  .PlowerhouseRoom
    db $28, "Plowerhouse Room", $FF
warnpc $E7B49C

org $E7B4AD
  .WorstRoomInTheGame
    db $28, "Worst Room In The Game", $FF
warnpc $E7B4C7

org $E7B4E5
  .Amphitheatre
    db $28, "Amphitheatre", $FF
warnpc $E7B4FF

org $E7B510
  .LNSpringBallMaze
    db $28, "LN Spring Ball Maze", $FF
warnpc $E7B52A

org $E7B55A
  .LNEscapePowerBombs
    db $28, "LN Escape Power Bombs", $FF
warnpc $E7B574

org $E7B585
  .RedKihunterShaft
    db $28, "Red Kihunter Shaft", $FF
warnpc $E7B59F

org $E7B5D5
  .Wasteland
    db $28, "Wasteland", $FF
warnpc $E7B5EF

org $E7B62B
  .MetalPiratesRoom
    db $28, "Metal Pirates Room", $FF
warnpc $E7B645

org $E7B656
  .ThreeMusketeersRoom
    db $28, "Three Musketeers' Room", $FF
warnpc $E7B670

org $E7B698
  .RidleyTankRoom
    db $28, "Ridley Tank Room", $FF
warnpc $E7B6B2

org $E7B6C1
  .ScrewAttackRoom
    db $28, "Screw Attack Room", $FF
warnpc $E7B6DB

org $E7B6EE
  .LNFirefleaRoom
    db $28, "LN Fireflea Room", $FF
warnpc $E7B708

org $E7B741
  .LowerNorfairSaveRoom
    db $28, "Lower Norfair Save Room", $FF
warnpc $E7B75B

org $E7C98E
  .BowlingAlley
    db $28, "Bowling Alley", $FF
warnpc $E7C9A8

org $E7CA08
  .WreckedShipEntrance
    db $28, "Wrecked Ship Entrance", $FF
warnpc $E7CA22

org $E7CA52
  .Attic
    db $28, "Attic", $FF
warnpc $E7CA6C

org $E7CAAE
  .AssemblyLine
    db $28, "Assembly Line", $FF
warnpc $E7CAC8

org $E7CAF6
  .WreckedShipMainShaft
    db $28, "Wrecked Ship Main Shaft", $FF
warnpc $E7CB10

org $E7CB8B
  .SpikyDeathRoom
    db $28, "Spiky Death Room", $FF
warnpc $E7CBA5

org $E7CBD5
  .ElectricDeathRoom
    db $28, "Electric Death Room", $FF
warnpc $E7CBEF

org $E7CC27
  .WreckedShipETank
    db $28, "Wrecked Ship E-Tank", $FF
warnpc $E7CC41

org $E7CC6F
  .Basement
    db $28, "Basement", $FF
warnpc $E7CC89

org $E7CCCB
  .WreckedShipMapRoom
    db $28, "Wrecked Ship Map Room", $FF
warnpc $E7CCE5

org $E7CD13
  .PhantoonRoom
    db $28, "Phantoon's Room", $FF
warnpc $E7CD2D

org $E7CD5C
  .SpongeBath
    db $28, "Sponge Bath", $FF
warnpc $E7CD76

org $E7CDA8
  .WSWestSuperRoom
    db $28, "WS West Super Room", $FF
warnpc $E7CDC2

org $E7CDF1
  .WSEastSuperRoom
    db $28, "WS East Super Room", $FF
warnpc $E7CE0B

org $E7CE40
  .GravitySuitRoom
    db $28, "Gravity Suit Room", $FF
warnpc $E7CE5A

org $E7CE8A
  .WreckedShipSaveRoom
    db $28, "Wrecked Ship Save Room", $FF
warnpc $E7CEA4

org $E7CED2
  .GlassTunnelSaveRoom
    db $28, "Glass Tunnel Save Room", $FF
warnpc $E7CEEC

org $E7CEFB
  .GlassTunnel
    db $28, "Glass Tunnel", $FF
warnpc $E7CF15

org $E7CF54
  .WestTunnel
    db $28, "West Tunnel", $FF
warnpc $E7CF6E

org $E7CF80
  .EastTunnel
    db $28, "East Tunnel", $FF
warnpc $E7CF9A

org $E7CFC9
  .MainStreet
    db $28, "Main Street", $FF
warnpc $E7CFE3

org $E7D017
  .FishTank
    db $28, "Fish Tank", $FF
warnpc $E7D031

org $E7D055
  .MamaTurtleRoom
    db $28, "Mama Turtle Room", $FF
warnpc $E7D06F

org $E7D08A
  .CrabTunnel
    db $28, "Crab Tunnel", $FF
warnpc $E7D0A4

org $E7D0B9
  .MtEverest
    db $28, "Mt. Everest", $FF
warnpc $E7D0D3

org $E7D104
  .RedFishRoom
    db $28, "Red Fish Room", $FF
warnpc $E7D11E

org $E7D13B
  .WateringHole
    db $28, "Watering Hole", $FF
warnpc $E7D155

org $E7D16D
  .NWestMaridiaBugRoom
    db $28, "N.West Maridia Bug Room", $FF
warnpc $E7D187

org $E7D1A3
  .CrabShaft
    db $28, "Crab Shaft", $FF
warnpc $E7D1BD

org $E7D1DD
  .PseudoPlasmaSpark
    db $28, "Pseudo Plasma Spark", $FF
warnpc $E7D1F7

org $E7D21C
  .CrabHole
    db $28, "Crab Hole", $FF
warnpc $E7D236

org $E7D252
  .WestSandHallTunnel
    db $28, "West Sand Hall Tunnel", $FF
warnpc $E7D26C

org $E7D27E
  .PlasmaTutorialRoom
    db $28, "Plasma Tutorial Room", $FF
warnpc $E7D298

org $E7D2AA
  .PlasmaRoom
    db $28, "Plasma Room", $FF
warnpc $E7D2C4

org $E7D2D9
  .ThreadTheNeedleRoom
    db $28, "Thread The Needle Room", $FF
warnpc $E7D2F3

org $E7D30B
  .MaridiaElevatorRoom
    db $28, "Maridia Elevator Room", $FF
warnpc $E7D325

org $E7D340
  .PlasmaSparkRoom
    db $28, "Plasma Spark Room", $FF
warnpc $E7D35A

org $E7D387
  .KassiuzRoom
    db $28, "Kassiuz Room", $FF
warnpc $E7D3A1

org $E7D3B6
  .MaridiaMapRoom
    db $28, "Maridia Map Room", $FF
warnpc $E7D3D0

org $E7D3DF
  .ForgottenHighwaySave
    db $28, "Forgotten Highway Save", $FF
warnpc $E7D3F9

org $E7D408
  .Toilet
    db $28, "Toilet", $FF
warnpc $E7D422

org $E7D433
  .BugSandHole
    db $28, "Bug Sand Hole", $FF
warnpc $E7D44D

org $E7D461
  .WestSandHall
    db $28, "West Sand Hall", $FF
warnpc $E7D47B

org $E7D48E
  .Oasis
    db $28, "Oasis", $FF
warnpc $E7D4A8

org $E7D4C2
  .EastSandHall
    db $28, "East Sand Hall", $FF
warnpc $E7D4DC

org $E7D4EF
  .WestSandHole
    db $28, "West Sand Hole", $FF
warnpc $E7D509

org $E7D51E
  .EastSandHole
    db $28, "East Sand Hole", $FF
warnpc $E7D538

org $E7D54D
  .WestAqueductQuicksand
    db $28, "West Aqueduct Quicksand", $FF
warnpc $E7D567

org $E7D57A
  .EastAqueductQuicksand
    db $28, "East Aqueduct Quicksand", $FF
warnpc $E7D594

org $E7D5A7
  .Aqueduct
    db $28, "Aqueduct", $FF
warnpc $E7D5C1

org $E7D5EC
  .ButterflyRoom
    db $28, "Butterfly Room", $FF
warnpc $E7D606

org $E7D617
  .BotwoonHallway
    db $28, "Botwoon Hallway", $FF
warnpc $E7D631

org $E7D646
  .PantsRoom
    db $28, "Pants Room", $FF
warnpc $E7D660

org $E7D69A
  .EastPantsRoom
    db $28, "East Pants Room", $FF
warnpc $E7D6B4

org $E7D6D0
  .SpringBallRoom
    db $28, "Spring Ball Room", $FF
warnpc $E7D6EA

org $E7D6FD
  .BelowBotwoonETank
    db $28, "Below Botwoon E-Tank", $FF
warnpc $E7D717

org $E7D72A
  .Colosseum
    db $28, "Colosseum", $FF
warnpc $E7D744

org $E7D765
  .AqueductSaveRoom
    db $28, "Aqueduct Save Room", $FF
warnpc $E7D77F

org $E7D78F
  .ThePreciousRoom
    db $28, "The Precious Room", $FF
warnpc $E7D7A9

org $E7D7E4
  .BotwoonETankRoom
    db $28, "Botwoon E-Tank Room", $FF
warnpc $E7D7FE

org $E7D81A
  .DraygonSaveRoom
    db $28, "Draygon Save Room", $FF
warnpc $E7D834

org $E7D845
  .MaridiaMissileRefill
    db $28, "Maridia Missile Refill", $FF
warnpc $E7D85F

org $E7D86E
  .PlasmaBeachQuicksand
    db $28, "Plasma Beach Quicksand", $FF
warnpc $E7D888

org $E7D898
  .BotwoonQuicksandRoom
    db $28, "Botwoon Quicksand Room", $FF
warnpc $E7D8B2

org $E7D8C5
  .ShaktoolRoom
    db $28, "Shaktool Room", $FF
warnpc $E7D8DF

org $E7D913
  .HalfieClimbRoom
    db $28, "Halfie Climb Room", $FF
warnpc $E7D92D

org $E7D95E
  .BotwoonRoom
    db $28, "Botwoon's Room", $FF
warnpc $E7D978

org $E7D9AA
  .SpaceJumpRoom
    db $28, "Space Jump Room", $FF
warnpc $E7D9C4

org $E7D9D4
  .MaridiaEnergyRefill
    db $28, "Maridia Energy Refill", $FF
warnpc $E7D9EE

org $E7D9FE
  .WestCactusAlleyRoom
    db $28, "West Cactus Alley Room", $FF
warnpc $E7DA18

org $E7DA2B
  .EastCactusAlleyRoom
    db $28, "East Cactus Alley Room", $FF
warnpc $E7DA45

org $E7DA60
  .DraygonRoom
    db $28, "Draygon's Room", $FF
warnpc $E7DA7A

org $E7DAAE
  .TourianFirstRoom
    db $28, "Tourian First Room", $FF
warnpc $E7DAC8

org $E7DAE1
  .MetroidRoom1
    db $28, "Metroid Room 1", $FF
warnpc $E7DAFB

org $E7DB31
  .MetroidRoom2
    db $28, "Metroid Room 2", $FF
warnpc $E7DB4B

org $E7DB7D
  .MetroidRoom3
    db $28, "Metroid Room 3", $FF
warnpc $E7DB97

org $E7DBCD
  .MetroidRoom4
    db $28, "Metroid Room 4", $FF
warnpc $E7DBE7

org $E7DC19
  .BlueHopperRoom
    db $28, "Blue Hopper Room", $FF
warnpc $E7DC33

org $E7DC65
  .DustTorizoRoom
    db $28, "Dust Torizo Room", $FF
warnpc $E7DC7F

org $E7DCB1
  .BigBoyRoom
    db $28, "Big Boy Room", $FF
warnpc $E7DCCB

org $E7DCFF
  .SeaweedRoom
    db $28, "Seaweed Room", $FF
warnpc $E7DD19

org $E7DD2E
  .TourianRechargeRoom
    db $28, "Tourian Recharge Room", $FF
warnpc $E7DD48

org $E7DD58
  .MotherBrainRoom
    db $28, "Mother Brain Room", $FF
warnpc $E7DD72

org $E7DDC4
  .TourianEyeDoorRoom
    db $28, "Tourian Eye Door Room", $FF
warnpc $E7DDDE

org $E7DDF3
  .RinkaShaft
    db $28, "Rinka Shaft", $FF
warnpc $E7DE0D

org $E7DE23
  .MotherBrainSaveRoom
    db $28, "Mother Brain Save Room", $FF
warnpc $E7DE3D

org $E7DE4D
  .TourianEscapeRoom1
    db $28, "Tourian Escape Room 1", $FF
warnpc $E7DE67

org $E7DE7A
  .TourianEscapeRoom2
    db $28, "Tourian Escape Room 2", $FF
warnpc $E7DE94

org $E7DEA7
  .TourianEscapeRoom3
    db $28, "Tourian Escape Room 3", $FF
warnpc $E7DEC1

org $E7DEDE
  .TourianEscapeRoom4
    db $28, "Tourian Escape Room 4", $FF
warnpc $E7DEF8

org $E7DF1B
  .UpperTourianSaveRoom
    db $28, "Upper Tourian Save Room", $FF
warnpc $E7DF35

org $E7DF45
  .CeresElevatorRoom
    db $28, "Ceres Elevator Room", $FF
warnpc $E7DF5F

org $E7DF8D
  .FallingTileRoom
    db $28, "Falling Tile Room", $FF
warnpc $E7DFA7

org $E7DFD7
  .MagnetStairsRoom
    db $28, "Magnet Stairs Room", $FF
warnpc $E7DFF1

org $E7E021
  .DeadScientistRoom
    db $28, "Dead Scientist Room", $FF
warnpc $E7E03B

org $E7E06B
  .58Escape
    db $28, "58 Escape", $FF
warnpc $E7E085

org $E7E0B5
  .CeresRidleyRoom
    db $28, "Ceres Ridley's Room", $FF
warnpc $E7E0CF

org $E7E82C
  .DebugRoom
    db $28, "Debug Room", $FF
warnpc $E7E844

print pc, " roomnames end"

